# This code is used to store the data for the main application.

def data():
    information = {
    "sao paulo": 25,
    "rio de janeiro": 28,
    "belo horizonte": 24,
    "brasilia": 26,
    "salvador": 29,
    "recife": 27,
    "fortaleza": 30,
    "natal": 29,
    "joao pessoa": 28,
    "maceio": 29,
    "aracaju": 28,
    "teresina": 31,
    "sao luis": 30,
    "belem": 29,
    "manaus": 30,
    "porto velho": 32,
    "rio branco": 31,
    "boa vista": 33,
    "macapa": 30,
    "palmas": 29,
    "goiania": 26,
    "cuiaba": 27,
    "campo grande": 25,
    "curitiba": 20,
    "florianopolis": 21,
    "porto alegre": 19,
    "caxias do sul": 17,
    "pelotas": 18,
    "santa maria": 18,
    "londrina": 22,
    "maringa": 23,
    "cascavel": 22,
    "foz do iguacu": 24,
    "chapeco": 21,
    "joinville": 22,
    "blumenau": 21,
    "itajai": 22,
    "balneario camboriu": 23,
    "sao jose": 21,
    "vitoria": 26,
    "vila velha": 27,
    "serra": 26,
    "cariacica": 26,
    "guarapari": 27,
    "campos dos goytacazes": 24,
    "niteroi": 25,
    "petropolis": 23,
    "teresopolis": 22,
    "volta redonda": 24,
    "resende": 23,
    "new york": 18,
    "los angeles": 20,
    "chicago": 16,
    "houston": 27,
    "phoenix": 30,
    "miami": 28,
    "orlando": 27,
    "tampa": 26,
    "atlanta": 24,
    "boston": 15,
    "san francisco": 17,
    "san jose": 18,
    "seattle": 14,
    "portland": 16,
    "denver": 13,
    "dallas": 26,
    "austin": 25,
    "san antonio": 27,
    "el paso": 28,
    "las vegas": 29,
    "london": 15,
    "manchester": 14,
    "birmingham": 15,
    "liverpool": 14,
    "leeds": 13,
    "paris": 17,
    "lyon": 18,
    "marseille": 19,
    "nice": 18,
    "toulouse": 17,
    "berlin": 14,
    "hamburg": 15,
    "munich": 16,
    "frankfurt": 15,
    "cologne": 14,
    "madrid": 19,
    "barcelona": 20,
    "valencia": 21,
    "seville": 22,
    "bilbao": 18,
    "rome": 21,
    "milan": 20,
    "turin": 19,
    "naples": 23,
    "florence": 20
    }
    
    return information

